security:

  oauth2:

    client:

      clientId: cenergy-client

      clientSecret: 123456

      accessTokenUri: http://localhost:8090/auth/oauth/token

      userAuthorizationUri: http://localhost:8090/auth/oauth/authorize

      clientAuthenticationScheme: form

    resource:

      userInfoUri: http://localhost:8090/auth/me
      

logging:
  level:
    org.springframework.security: DEBUG
